const data = {
  products: [
    {
      name: "Boho wall decor",
      id: 1,
      category: "Decor",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 0,
      brand: "rldh",
      rating: 4.5,
      numReviews: 10,
      description: "Good home decor",
    },
    {
      name: "Social Worker Shirt",
      id: 2,
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 12,
      brand: "rldh",
      rating: 4.5,
      numReviews: 8,
      description: "Good home shirt",
    },
    {
      name: "The Boston Cardigan",
      id: 3,
      category: "Cardigan",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 10,
      brand: "rldh",
      rating: 4.5,
      numReviews: 10,
      description: "Good home decor",
    },
    {
      name: "Boho wall decor 2",
      id: 4,
      category: "Decor",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 10,
      brand: "rldh",
      rating: 4.5,
      numReviews: 10,
      description: "Good home decor",
    },
  ],
};

export default data;
