export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";
export const CURRENCY_CHANGE_REQUEST = "CURRENCY_CHANGE_REQUEST";
export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const SHOP_PAGE_PRODUCTS_UPDATED = "SHOP_PAGE_PRODUCTS_UPDATED";
export const FAVORITES_UPDATED = "FAVORITES_UPDATED";
